import {
  ArrowUpRightIcon as ArrowUpRight,
  ArrowsOutSimpleIcon as ArrowsOutSimple,
  ArrowsInSimpleIcon as ArrowsInSimple,
  ClipboardTextIcon as ClipboardText,
  MinusIcon as Minus,
  MonitorIcon as Monitor,
  CheckCircleIcon as CheckCircle,
  EyeIcon as Eye,
  EyeClosedIcon as EyeClosed,
  MagnifyingGlassIcon as MagnifyingGlass,
  WarningCircleIcon as Warning,
  XCircleIcon as X,
  FileIcon as File,
  InfoIcon as Info,
  CaretDownIcon as CaretDown,
  CaretUpIcon as CaretUp,
  FunnelIcon as Funnel,
  DotIcon as Dot,
  CircleDashedIcon as CircleDashed,
  ArrowLeftIcon as ArrowLeft,
  CircleIcon as Circle,
  ArrowRightIcon as ArrowRight,
  ArrowUpIcon as ArrowUp,
  ArrowDownIcon as ArrowDown,
  MagnifyingGlassMinusIcon as MagnifyingGlassMinus,
  SortAscendingIcon as SortAscending,
  SortDescendingIcon as SortDescending,
  RowsIcon as Rows,
  MoonIcon as Moon,
  HashIcon as Hash,
  DatabaseIcon as Database,
  SunIcon as Sun,
  UploadIcon as Upload,
  CaretDoubleLeftIcon as CaretDoubleLeft,
  CaretLeftIcon as CaretLeft,
  CaretDoubleRightIcon as CaretDoubleRight,
  CaretRightIcon as CaretRight,
  UploadSimpleIcon as UploadSimple,
  ClockClockwiseIcon as ClockClockwise,
  ClockCountdownIcon as ClockCountdown,
  ClockCounterClockwiseIcon as ClockCounterClockwise,
  ArrowClockwiseIcon as ArrowClockwise,
  ListNumbersIcon as ListNumbers,
} from "@phosphor-icons/react";

export const Icons = {
  ArrowClockwise,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowsInSimple,
  ArrowsOutSimple,
  ArrowUp,
  ArrowUpRight,
  CaretDoubleLeft,
  CaretDoubleRight,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CheckCircle,
  Circle,
  CircleDashed,
  ClipboardText,
  ClockClockwise,
  ClockCountdown,
  ClockCounterClockwise,
  Database,
  Dot,
  Eye,
  EyeClosed,
  File,
  Funnel,
  Hash,
  Info,
  ListNumbers,
  MagnifyingGlass,
  MagnifyingGlassMinus,
  Minus,
  Monitor,
  Moon,
  Rows,
  SortAscending,
  SortDescending,
  Sun,
  Upload,
  UploadSimple,
  Warning,
  X,
};
